# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  dev:
    cmds:
      - go tool air
    silent: true
  db:
    cmds:
      - docker compose up
  migrate:up:
    cmds:
      - migrate -database postgres://postgres:postgres@localhost:5433/greenlightdb?sslmode=disable -path ./migrations up
  migrate:down:
    cmds:
      - migrate -database postgres://postgres:postgres@localhost:5433/greenlightdb?sslmode=disable -path ./migrations down 1
  migrate:goto:
    cmds:
      - migrate -database postgres://postgres:postgres@localhost:5433/greenlightdb?sslmode=disable -path ./migrations goto {{.number}}
  migrate:version:
    cmds:
      - migrate -database postgres://postgres:postgres@localhost:5433/greenlightdb?sslmode=disable -path ./migrations version
  migrate:create:
    cmds:
      - migrate create -ext sql -dir ./migrations -seq {{.name}}
  load-testing:
    cmds:
      - echo "GET http://localhost:4000/v1/healthcheck/" | vegeta attack -duration=1s -rate=10/1s
