# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  dev:
    cmds:
      - go tool air
    silent: true
  db:
    cmds:
      - docker compose up
  migrate:up:
    cmds:
      - migrate -database postgres://postgres:postgres@localhost:5433/greenlightdb?sslmode=disable -path ./migrations up
  migrate:down:
    cmds:
      - migrate -database postgres://postgres:postgres@localhost:5433/greenlightdb?sslmode=disable -path ./migrations down
  migrate:create:
    cmds:
      - migrate create -ext sql -dir ./migrations -seq {{.name}}
